# Generated by Django 6.1 on 2026-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
