# Generated by Django 6.1 on 2026-08-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
