# Generated by Django 6.1 on 2026-08-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
    ]
